name = "cleam"
version = "1.5.0"
description = "Cleam for clean Gleam. Detect unused exports."
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "cleam" }
gleam = ">= 1.1.0"

[dependencies]
gleam_stdlib = "~> 0.37"
fswalk = "~> 3.0"
simplifile = "~> 1.6"
glance = "~> 0.10"

[dev-dependencies]
gleeunit = "~> 1.0"
