name = "cleam"
version = "2.0.0"
description = "Cleam for clean Gleam. Detect unused exports."
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "cleam" }
gleam = ">= 1.4.0"

[dependencies]
gleam_stdlib = "~> 0.37"
gleam_yielder = "~> 1.0"
fswalk = "~> 3.0"
simplifile = "~> 2.0"
glance = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
